[project]
name = "ctdam"
version = "2.4.0"
description = "Library for conversion, processing and plotting of CTD data."
authors = [{ name = "Emil Michels", email = "emil.michels@iow.de" }]
readme = "README.md"
keywords = [
    "CTD",
    "conversion",
    "parser",
    "processing",
    "visualization",
    "oceanography",
    "seabird",
    "data",
]
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Development Status :: 5 - Production/Stable",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Oceanography",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
requires-python = ">=3.12"
dependencies = [
    "xmltodict>=0.13.0",
    "docstring-parser>=0.17.0",
    "tomlkit>=0.12.3",
    "tqdm>=4.67.3",
    "numpydoc>=1.10.0",
    "netCDF4>=1.7.4",
    "xarray>=2026.7.0",
    "gsw-xarray>=0.5.0",
    "odf-sbe>=0.3.0",
    "munch>=4.0.0",
    "scipy>=1.18.1",
    "matplotlib>=3.11.1",
]

[project.optional-dependencies]
cli = ["typer", "platformdirs"]
gui = ["customtkinter", "ctkmessagebox"]
vis = ["bokeh", "beautifulsoup4"]
all = [
    "bokeh",
    "beautifulsoup4",
    "typer",
    "customtkinter",
    "ctkmessagebox",
    "platformdirs",
]
test = [
    "pytest>=7.4.2",
    "pytest-xdist>=3.6.1",
    "pytest-cov>=7.0.0",
    "pytest-order>=1.3.0",
]
docs = [
    "sphinx>=8.1.3",
    "sphinx-autodoc-typehints>=2.5.0",
    "pyment>=0.3.3",
    "sphinx-copybutton>=0.5.2",
    "furo>=2024.8.6",
    "myst-parser>=4.0.1",
    "click-extra[sphinx]>=7.9.0",
]
release = ["python-semantic-release>=9.21.1", "gitpython==3.1.59"]

[project.urls]
Homepage = "https://github.com/DAM-CTD-Software/ctdam"
Repository = "https://github.com/DAM-CTD-Software/ctdam"
Documentation = "https://dam-ctd-software.github.io/ctdam"
Issues = "https://github.com/DAM-CTD-Software/ctdam/issues"
Changelog = "https://github.com/DAM-CTD-Software/ctdam/blob/main/CHANGELOG.md"

[project.scripts]
ctdam = "ctdam.entry.cli:app"

[tool.pytest.ini_options]
pythonpath = [".", "src", "src/ctdam"]
markers = ["long"]
filterwarnings = ['ignore::RuntimeWarning', "ignore::UserWarning"]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["ERA001"]
ignore = ["F403", "F821"]

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
version_variables = [".zenodo.json:version:nf"]
build_command = "uv build"
upload_to_vcs_release = true

[tool.coverage]
run.omit = ['src/ctdam/entry/*']
run.relative_files = true
report.skip_empty = true
report.sort = "Cover"

[tool.hatch.build.targets.wheel]
packages = ["src/ctdam"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
