[project]
name = "ctdam"
version = "1.0.0"
description = "Library to handle all steps when working with CTD data."
authors = [{ name = "Emil Michels", email = "emil.michels@iow.de" }]
readme = "README.rst"
keywords = [
    "CTD",
    "conversion",
    "parser",
    "processing",
    "visualization",
    "oceanography",
    "seabird",
    "data",
]
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Development Status :: 5 - Production/Stable",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Oceanography",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
requires-python = ">=3.12"
dependencies = [
    "seabirdscientific>=2.7.0",
    "xmltodict>=0.13.0",
    "docstring-parser>=0.17.0",
    "tomlkit>=0.12.3",
]

[project.optional-dependencies]
cli = ["typer", "platformdirs"]
gui = ["customtkinter", "ctkmessagebox"]
vis = ["bokeh", "beautifulsoup4"]
all = [
    "bokeh",
    "beautifulsoup4",
    "typer",
    "customtkinter",
    "ctkmessagebox",
    "platformdirs",
]
test = ["pytest>=7.4.2", "pytest-xdist>=3.6.1"]
docs = [
    "sphinx>=8.1.3",
    "sphinx-autodoc-typehints>=2.5.0",
    "pyment>=0.3.3",
    "sphinx-copybutton>=0.5.2",
    "furo>=2024.8.6",
]

[project.urls]
Homepage = "https://github.com/DAM-CTD-Software/ctdam"
Repository = "https://github.com/DAM-CTD-Software/ctdam"
Documentation = "https://ctdam.readthedocs.io"
Issues = "https://github.com/DAM-CTD-Software/ctdam/issues"
Changelog = "https://github.com/DAM-CTD-Software/ctdam/blob/main/CHANGELOG.md"

[project.scripts]
ctdam = "ctdam.entry.cli:app"

[tool.pytest.ini_options]
pythonpath = [".", "src", "src/ctdam"]
markers = ["seabird", "long"]
filterwarnings = ['ignore::RuntimeWarning', "ignore::UserWarning"]

[tool.ruff]
line-length = 79
extend-exclude = ['__init__.py']

[tool.ruff.lint]
select = ["ERA001"]
ignore = ["F403", "F821"]

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
version_variables = [".zenodo.json:version:nf"]
build_command = "uv build"
upload_to_vcs_release = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/ctdam"]
