import logging
import multiprocessing
import sys
import warnings
from collections import UserList
from pathlib import Path

import pandas as pd
import xarray as xr
from tqdm import tqdm

from ctdam.exceptions import (
    BinnedDataError,
    MissingParameterError,
    NoDataError,
)
from ctdam.parser import PARSEABLE_FILE_FORMATS
from ctdam.parser.read_ctd_data import parse
from ctdam.proc.workflow import Workflow
from ctdam.utils import get_unique_sensor_data
from ctdam.vis import basic_bokeh_plot, create_main_html

logger = logging.getLogger(__name__)


class Casts(UserList):
    """
    A structure to ease working with multiple ctd casts.

    Can work with ascii files, converted (.cnv) or non-converted (.hex), as
    well as data within python objects (CTDData). Automates the very basic
    actions ussually performs on these data: converting, processing, plotting
    and exporting. The cpu-heavy actions (convertion and processing) are
    calculated in parallel, using multithreading.

    Parameters
    ----------
    path_to_data : Path | str
        Path to target files
    ctd_data : list[CTDData] :
        A list of target CTDData objects
    processing_info : dict
        Processing configuration
    pattern : str
        A file pattern to filter the target files with
    plot : bool
        Whether to create .html plots of the target files
    show_plot : bool
        Whether to display the plots in a browser
    plot_dir : Path | str
        The directory to store the plots in

    Attributes
    ----------
    data: list
        A list of CTDData objects
    processing_info: dict
        A processing workflow as used in Procedure
    path_to_data: Path
        The input path to the data file(s)
    anomalous_data: list
        A list of data files that seem to be suspiciously small
    cruise: str
        The name of the cruise the data files were collected in
    sensor_info: list
        The sensor structure as generated by get_unique_sensor_data()
    plot_dir: Path
        A file path where generated data plots are saved to
    """

    def __init__(
        self,
        path_to_data: Path | str = "",
        ctd_data: list[xr.Dataset] = [],
        processing_info: dict = {},
        pattern: str = "",
        plot: bool = False,
        show_plot: bool = True,
        plot_dir: Path | str = "htmls",
        use_multiprocessing: bool = True,
    ):
        self.processing_info = processing_info
        self.plot_dir = plot_dir
        self.use_multiprocessing = use_multiprocessing
        self.anomalous_data = []
        if ctd_data:
            self.data = ctd_data
            if [Path(p.attrs["path_to_source_file"]).parent for p in ctd_data]:
                self.path_to_data = (
                    ctd_data[0].attrs["path_to_source_file"].parent
                )
            else:
                self.path_to_data = None
        elif path_to_data:
            self.path_to_data = Path(path_to_data)
            if self.path_to_data.is_dir():
                files = sorted(
                    [
                        file
                        for file in self.path_to_data.rglob(f"*{pattern}*")
                        if file.suffix in PARSEABLE_FILE_FORMATS
                    ]
                )
                if use_multiprocessing:
                    with multiprocessing.Pool() as pool:
                        self.data = list(
                            tqdm(
                                pool.imap_unordered(self.convert, files),
                                total=len(files),
                                desc="Cast conversion",
                                unit="cast",
                            )
                        )
                else:
                    self.data = [self.convert(file) for file in files]

            elif self.path_to_data.is_file():
                self.data = [self.convert(self.path_to_data)]
            else:
                sys.exit(f"Invalid input path: {path_to_data}")
            self.anomalous_data = self.check_converted_data()
        else:
            sys.exit(f"Invalid input: {ctd_data} or {path_to_data}")
        # check for empty directory/CTDData list
        if len(self.data) < 1:
            raise NoDataError(self.data)
        else:
            try:
                self.cruise = self.data[0].attrs["cruise"]
            except KeyError:
                self.cruise = ""
            # check, whether processing_info contained only infos for hex2py
            if "modules" in processing_info:
                if "hex2py" in processing_info["modules"]:
                    if len(processing_info["modules"]) == 1:
                        processing_info = {}
            if processing_info:
                self.process(processing_info)
            if plot:
                self.plot(show_plot)
            self.data = sorted(
                [d for d in self.data if isinstance(d, xr.Dataset)],
                key=lambda x: Path(x.attrs["path_to_source_file"]),
            )
            if self.anomalous_data:
                logger.error(
                    f"The following casts appear to be faulty:\n{
                        '\n'.join(
                            [
                                str(cast.attrs['path_to_source_file'])
                                for cast in self.anomalous_data
                            ]
                        )
                    }"
                )

    def convert(self, file: Path):
        """
        Converts .hex files.

        Can work with hex2py processing settings and hides all warnings.

        Parameters
        ----------
        file: Path :
            Path to target hex files

        """
        arguments = {}
        if "modules" in self.processing_info:
            if "hex2py" in self.processing_info["modules"]:
                arguments = self.processing_info["modules"]["hex2py"]
        try:
            with warnings.catch_warnings(action="ignore"):
                return parse(file, **arguments)
        except Exception as error:
            logger.error(f"Could not convert file {file}: {error}")
            self.anomalous_data.append(file)

    def check_converted_data(self) -> list[xr.Dataset]:
        """
        Basic output data size check.

        Catches very obvious test or wrong CTD data. These are saved in
        an anomalies attribute to allow human intervention.

        Returns
        -------
        A list of xarray Datasets that appear to be wrong.
        """
        self.data = [c for c in self.data if c is not None]
        anomalies = []
        passed_data = []
        for cast in self.data:
            if cast.access.binned:
                if cast.access.size < 10:
                    anomalies.append(cast)
                else:
                    passed_data.append(cast)
            else:
                if cast.access.size < 500:
                    anomalies.append(cast)
                else:
                    passed_data.append(cast)
        self.data = passed_data
        return anomalies

    def read_sensor_info(self):
        """
        Parses all sensor metadata in one structure.

        Usually, the sensor layout does not change during one cruise. But
        if it does, this function should detect that change and document
        it with a new list that displays the cast number and the differing
        sensor metadata.
        """
        self.sensor_info = get_unique_sensor_data(
            [cast.sensor_info for cast in sorted(self.data)]
        )
        if len(self.sensor_info) > 1:
            warnings.warn(
                "Sensor anomalies found. Please check the sensor_info attribute for details."
            )
            sensor_info = []
            for configuration in self.sensor_info:
                for sensor in configuration[1]:
                    sensor_info.append(sensor)
        else:
            sensor_info = self.sensor_info[0][1]

    def process(
        self,
        processing_info: dict,
        target_files: list[xr.Dataset] = [],
    ):
        """
        Applies the given processing workflow to all CTD data.

        Uses multiprocessing for parallel processing and tqdm to display
        the progress.

        Parameters
        ----------
        processing_info: dict :
            Processing workflow configuration

        target_files: list[xr.Dataset] :
            The files to process
        """
        target_files = target_files if target_files else self.data
        if self.use_multiprocessing:
            with multiprocessing.Pool() as pool:
                return list(
                    tqdm(
                        pool.starmap(
                            self._process_item,
                            [(a, processing_info) for a in target_files],
                        ),
                        total=len(target_files),
                        desc="Processing",
                        unit="cast",
                    )
                )
        else:
            if len(target_files) > 0:
                return [
                    self._process_item(ds, processing_info)
                    for ds in target_files
                ]
            else:
                raise TypeError("Could not determine processing target.")

    def _process_item(self, ds: xr.Dataset, proc_settings: dict):
        try:
            return Workflow(ds, proc_settings).output
        except (MissingParameterError, BinnedDataError, NoDataError) as error:
            logger.error(
                f"Could not perform processing workflow on {ds.attrs['path_to_source_file']}: {error}"
            )
            self.anomalous_data.append(ds)

    def plot(self, show_plot: bool = True):
        """
        Creates .html plots of the target data.

        Uses bokeh for interactive plotting and creates one 'main' .html
        that incorporates all individual cast plots.

        Parameters
        ----------
        show_plot: bool :
            Whether to open the plot in a browser
        """
        html_directory = str(self.path_to_data.parent.joinpath(self.plot_dir))
        for cast in self.data:
            try:
                basic_bokeh_plot(
                    ctd_data=cast,
                    output_directory=html_directory,
                    print_plot=True,
                    metadata=True,
                    show_plot=False,
                )
            except Exception:
                continue

        create_main_html(
            directory_path=html_directory,
            title=self.cruise,
            show_html=show_plot,
        )

    def to_tsv(self, file_name: str | Path | None = None):
        """
        Exports the target file data into one great .tsv file.

        Parameters
        ----------
        file_name: str | Path | None :
            The name of the exported file
        """
        file_name = f"{self.cruise}_CTD" if file_name is None else file_name

        if not hasattr(self, "df"):
            list_of_dfs = [cast.access.pandas_dataframe for cast in self.data]
            self.df = pd.concat(list_of_dfs, ignore_index=True)
        df_out = self.df.copy()

        # apply number formatting for each parameter
        for column in df_out.columns:
            try:
                df_out[column] = df_out[column].astype("float")
            except ValueError:
                continue
            for param in self.data[0]:
                if column == param:
                    if param == "pressure":
                        formatter = "{:.1f}"
                    else:
                        formatter = self.data[0].export._set_output_format(
                            param
                        )
                    df_out[column] = df_out[column].map(formatter.format)
        df_out.to_csv(
            path_or_buf=Path(file_name).with_suffix(".tab"),
            sep="\t",
            index=False,
        )
