import logging
from pathlib import Path

import xarray as xr

from ctdam.proc.modules.available_modules import map_proc_name_to_class
from ctdam.proc.settings import Configuration, IncompleteProcedureConfig


logger = logging.getLogger(__name__)


class Workflow:
    """
    Runs a couple of processing steps in sequence on one or more CTD data
    source files.

    It can use seabird internal processing modules, as well as custom ones.
    These can be in the form of independent windows exes or just pure python
    code. The input data can be .hex, .cnv or python data representations,
    predominantly CTDData. The input and all module and extra information
    is stored in a dict that usually will be generated by the settings
    Configuration module that reads a toml config.

    Parameters
    ----------
    configuration: dict | Configuration
        The information necessary to run a processing procedure.
    auto_run: bool = True
        Whether to autopilot the whole procedure.
    """

    def __init__(
        self,
        ds: xr.Dataset,
        configuration: dict | Configuration,
        auto_run: bool = True,
    ) -> None:
        self.ds = ds
        self.original_input = ds.copy(deep=True)
        if isinstance(configuration, Configuration):
            self.config = configuration.data
        else:
            self.config = configuration
        self.load_config()
        self.xmlcon = None
        if auto_run:
            self.output = self.run()

    def load_config(self):
        """
        Thorough input/format check of the processing configuration, that
        either stems from a .toml config file, or is a self-build dictionary.
        Checks for the presence of certain keys, and then, depending on their
        importance, either fails or sets default values.
        """
        self.output_dir = Path(
            self.check_config_entry(
                "output_dir",
                Path(self.ds.attrs["path_to_source_file"]).parent,
            )
        )
        if not self.output_dir.exists():
            self.output_dir.mkdir(parents=True)
        self.output_name = self.check_config_entry("output_name", None)
        self.output_type = self.check_config_entry("output_type", "internal")
        self.output_columns = self.check_config_entry("output_columns", "all")
        self.xmlcon = self.check_config_entry("xmlcon", None)
        self.bad_flag = self.check_config_entry("bad_flag", -9.990e-29)
        self.downcast_only = self.check_config_entry("downcast_only", True)
        self.remove_flags = self.check_config_entry("remove_flags", False)
        try:
            self.modules = self.config["modules"].copy()
            assert isinstance(self.modules, dict)
            for module in list(self.modules.values()):
                assert isinstance(module, dict)
        except KeyError:
            raise IncompleteProcedureConfig(
                "No processing modules given. Aborting."
            )
        except AssertionError as error:
            raise IncompleteProcedureConfig(
                f"Module information is misconfigured: {error}. Aborting."
            )

    def check_config_entry(self, key: str, default_value):
        """Handles configuration file entries."""
        try:
            value = self.config[key]
        except KeyError:
            value = default_value
        else:
            if len(str(value)) == 0:
                value = default_value
        return value

    def new_file_path(self, file: Path = Path(".")) -> Path:
        """
        Creates the new output file path.

        Takes the file type directory or the given output directory and joins
        them with the given output name.

        Parameters
        ----------
        file: Path
            The current path to the target file.

        Returns
        -------
        The new path to write the target file to.
        """
        new_name = self.output_name if self.output_name else file.name
        directory = self.output_dir
        return directory.joinpath(new_name)

    def run(self) -> xr.Dataset:
        """
        Performs the processing on all target files.

        This is the 'main' method of the procedure. All previous methods
        prepare data for this method to then finally transform the input files
        into the wanted format.
        The main purpose of this method is the coordination of the two
        different forms of processing modules: standalone executables with
        config files, mainly Sea-Bird processing modules, and python-internal
        classes that implement the Module interface. The caveats are mainly
        the switching from one form to the other. This for example results in
        a in or out parsing of a CnvFile object.

        Returns
        -------
        A CTDData instance.
        """
        output_module_info = {}
        for module_name, module_info in self.modules.items():
            proc_module = map_proc_name_to_class(module_name)
            output_module_info[module_name] = proc_module
            self.ds = proc_module(
                ds=self.ds,
                arguments=module_info,
            )
        # handle output
        if self.output_type == "cnv":
            self.ds.export.to_cnv(
                file_path=self.new_file_path(),
                bad_flag=self.bad_flag,
            )
        self.modules = output_module_info
        return self.ds
