name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'python-semantic-release')"
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v7.3.1
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          uv sync --all-extras
          uv pip install python-semantic-release

      - name: Python Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          uv run semantic-release -v version --changelog
          uv run semantic-release -v publish

      - name: Check if dist files exist
        id: check_dist
        run: |
          if [ -d "dist" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish to PyPI
        if: steps.check_dist.outputs.exists == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Build docs
        if: "contains(github.event.head_commit.message, 'docs')"
        run: |
          mkdir docs/build -p
          cp docs/EMB356_11-1.html docs/build
          uv run sphinx-apidoc -feo docs/source src/ctdam
          uv run sphinx-build -b html docs docs/build

      - name: Deploy to gh-pages
        if: "contains(github.event.head_commit.message, 'docs')"
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          publish_branch: gh-pages
