name: Test

on:
  pull_request:
    branches: "v2-refactor"
    paths:
      - 'src/**'
      - 'tests/**'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/ruff-action@v3.6.1

      - name: Run ruff linter
        run: ruff check src tests

      - name: Run ruff formatter check
        run: ruff format --check src tests

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v7.3.1
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: uv sync --extra test --extra all

      - name: Set up sbs_data submodule
        run: |
          git submodule init
          git submodule update

      - name: Run tests
        run: uv run pytest -L -n auto
